### ISSUE TITLE
GECO theme for website

### ISSUE THREAD

**Issue by stineb** [geco-bern/sofunCalVal#15]
@fabern

**Comment by fabern** [comment]
- [ ] use resources from `rsofun` for this:
    - objective: https://geco-bern.github.io/rsofun/articles/new_cost_function.html
    - solution: https://github.com/geco-bern/rsofun/blob/2d8fdedbf4d38a2929b72a42b720a6bc672a039a/.github/workflows/deploy_docs.yaml#L37

**Comment by fabern** [comment]
Solution was to add:

https://github.com/geco-bern/sofunCalVal/blob/79545926c0ad3faf3f4ac8a007fc4fdc188a56a8/_pkgdown.yml#L1-L5

on top of the already existing:

https://github.com/geco-bern/sofunCalVal/blob/79545926c0ad3faf3f4ac8a007fc4fdc188a56a8/.github/workflows/deploy_pkgdown.yml#L33
